config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'calendar#show'

  get 'calendar/show'
  post 'calendar/update'

  resources :executed_chores
  resources :scheduled_chores
  resources :chores
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/executed_chore.rb
# == Schema Information
#
# Table name: executed_chores
#
#  id         :integer          not null, primary key
#  chore_id   :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  completed  :boolean          default(FALSE)
#

class ExecutedChore < ApplicationRecord
  belongs_to :user
  belongs_to :chore

  def self.day_chores(date)
    ExecutedChore.where(created_at: date.midnight..date.end_of_day)
  end

  def self.update_completion(params, current_user)
    ExecutedChore.day_chores(Date.current).where(user: current_user).each do |day_chore|
      completed = params['chore'].present? and params['chore'][day_chore.id.to_s].present?
      day_chore.update_attribute(:completed, completed)
    end
  end

  def self.week_score(user, offset = 0)
    first_date = (Date.current.beginning_of_week + offset.day).beginning_of_week
    last_date = first_date + 7.day
    all_chores = ExecutedChore.where(user: user, created_at: first_date.midnight..last_date.end_of_day)
    return 0 if all_chores.count == 0
    completed_cores = all_chores.where(completed: true)
    (completed_cores.count.to_f/all_chores.count * 100).to_i
  end

  def html_class
    completed == true ? 'completed-chore':'uncompleted-chore'
  end
end

app/controllers/executed_chores_controller.rb
class ExecutedChoresController < ApplicationController
  before_action :set_executed_chore, only: [:show, :edit, :update, :destroy]

  # GET /executed_chores
  # GET /executed_chores.json
  def index
    @executed_chores = ExecutedChore.all
  end

  # GET /executed_chores/1
  # GET /executed_chores/1.json
  def show
  end

  # GET /executed_chores/new
  def new
    @executed_chore = ExecutedChore.new
  end

  # GET /executed_chores/1/edit
  def edit
  end

  # POST /executed_chores
  # POST /executed_chores.json
  def create
    @executed_chore = ExecutedChore.new(executed_chore_params)

    respond_to do |format|
      if @executed_chore.save
        format.html { redirect_to @executed_chore, notice: 'Executed chore was successfully created.' }
        format.json { render :show, status: :created, location: @executed_chore }
      else
        format.html { render :new }
        format.json { render json: @executed_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /executed_chores/1
  # PATCH/PUT /executed_chores/1.json
  def update
    respond_to do |format|
      if @executed_chore.update(executed_chore_params)
        format.html { redirect_to @executed_chore, notice: 'Executed chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @executed_chore }
      else
        format.html { render :edit }
        format.json { render json: @executed_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /executed_chores/1
  # DELETE /executed_chores/1.json
  def destroy
    @executed_chore.destroy
    respond_to do |format|
      format.html { redirect_to executed_chores_url, notice: 'Executed chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_executed_chore
      @executed_chore = ExecutedChore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def executed_chore_params
      params.require(:executed_chore).permit(:chore_id, :user_id)
    end
end

app/helpers/executed_chores_helper.rb
module ExecutedChoresHelper
end

app/views/executed_chores/_form.html.erb
<%= form_for(executed_chore) do |f| %>
  <% if executed_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(executed_chore.errors.count, "error") %> prohibited this executed_chore from being saved:</h2>

      <ul>
      <% executed_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chore_id %>
    <%= f.number_field :chore_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/executed_chores/edit.html.erb
<h1>Editing Executed Chore</h1>

<%= render 'form', executed_chore: @executed_chore %>

<%= link_to 'Show', @executed_chore %> |
<%= link_to 'Back', executed_chores_path %>

app/views/executed_chores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Executed Chores</h1>

<table>
  <thead>
    <tr>
      <th>Chore</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @executed_chores.each do |executed_chore| %>
      <tr>
        <td><%= executed_chore.chore_id %></td>
        <td><%= executed_chore.user_id %></td>
        <td><%= link_to 'Show', executed_chore %></td>
        <td><%= link_to 'Edit', edit_executed_chore_path(executed_chore) %></td>
        <td><%= link_to 'Destroy', executed_chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Executed Chore', new_executed_chore_path %>

app/views/executed_chores/new.html.erb
<h1>New Executed Chore</h1>

<%= render 'form', executed_chore: @executed_chore %>

<%= link_to 'Back', executed_chores_path %>

app/views/executed_chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chore:</strong>
  <%= @executed_chore.chore_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @executed_chore.user_id %>
</p>

<%= link_to 'Edit', edit_executed_chore_path(@executed_chore) %> |
<%= link_to 'Back', executed_chores_path %>