config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'calendar#show'

  get 'calendar/show'
  post 'calendar/update'

  resources :executed_chores
  resources :scheduled_chores
  resources :chores
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/scheduled_chore.rb
# == Schema Information
#
# Table name: scheduled_chores
#
#  id         :integer          not null, primary key
#  chore_id   :integer
#  user_id    :integer
#  monday     :boolean
#  tuesday    :boolean
#  wednesday  :boolean
#  thursday   :boolean
#  friday     :boolean
#  saturday   :boolean
#  sunday     :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  active     :boolean
#

class ScheduledChore < ApplicationRecord
  belongs_to :chore
  belongs_to :user

  DOW_TO_FIELD = %w"sunday monday tuesday wednesday thursday friday saturday"

  def self.create_day_tasks
    ScheduledChore.where('active' => true,  today_dow => true).each do |scheduled_chore|
      ExecutedChore.create(chore: scheduled_chore.chore, user: scheduled_chore.user)
    end
  end

  def self.today_dow
    date_dow(Date.today)
  end

  def self.date_dow(date)
    DOW_TO_FIELD[date.wday]
  end

  def self.day_chores(date)
    ScheduledChore.where('active' => true,  date_dow(date) => true)
  end

  def html_class
    'scheduled-chore'
  end
end

app/controllers/scheduled_chores_controller.rb
class ScheduledChoresController < ApplicationController
  before_action :set_scheduled_chore, only: [:show, :edit, :update, :destroy]

  # GET /scheduled_chores
  # GET /scheduled_chores.json
  def index
    @scheduled_chores = ScheduledChore.all
  end

  # GET /scheduled_chores/1
  # GET /scheduled_chores/1.json
  def show
  end

  # GET /scheduled_chores/new
  def new
    @scheduled_chore = ScheduledChore.new
  end

  # GET /scheduled_chores/1/edit
  def edit
  end

  # POST /scheduled_chores
  # POST /scheduled_chores.json
  def create
    @scheduled_chore = ScheduledChore.new(scheduled_chore_params)

    respond_to do |format|
      if @scheduled_chore.save
        format.html { redirect_to @scheduled_chore, notice: 'Scheduled chore was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled_chore }
      else
        format.html { render :new }
        format.json { render json: @scheduled_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_chores/1
  # PATCH/PUT /scheduled_chores/1.json
  def update
    respond_to do |format|
      if @scheduled_chore.update(scheduled_chore_params)
        format.html { redirect_to @scheduled_chore, notice: 'Scheduled chore was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_chore }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_chore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_chores/1
  # DELETE /scheduled_chores/1.json
  def destroy
    @scheduled_chore.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_chores_url, notice: 'Scheduled chore was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_chore
      @scheduled_chore = ScheduledChore.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_chore_params
      params.require(:scheduled_chore).permit(:chore_id, :user_id, :monday, :tuesday, :wednesday, :thursday, :friday, :saturday, :sunday)
    end
end

app/helpers/scheduled_chores_helper.rb
module ScheduledChoresHelper
end

app/views/scheduled_chores/_form.html.erb
<%= form_for(scheduled_chore) do |f| %>
  <% if scheduled_chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(scheduled_chore.errors.count, "error") %> prohibited this scheduled_chore from being saved:</h2>

      <ul>
      <% scheduled_chore.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :chore_id %>
    <%= f.number_field :chore_id %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :monday %>
    <%= f.check_box :monday %>
  </div>

  <div class="field">
    <%= f.label :tuesday %>
    <%= f.check_box :tuesday %>
  </div>

  <div class="field">
    <%= f.label :wednesday %>
    <%= f.check_box :wednesday %>
  </div>

  <div class="field">
    <%= f.label :thursday %>
    <%= f.check_box :thursday %>
  </div>

  <div class="field">
    <%= f.label :friday %>
    <%= f.check_box :friday %>
  </div>

  <div class="field">
    <%= f.label :saturday %>
    <%= f.check_box :saturday %>
  </div>

  <div class="field">
    <%= f.label :sunday %>
    <%= f.check_box :sunday %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scheduled_chores/edit.html.erb
<h1>Editing Scheduled Chore</h1>

<%= render 'form', scheduled_chore: @scheduled_chore %>

<%= link_to 'Show', @scheduled_chore %> |
<%= link_to 'Back', scheduled_chores_path %>

app/views/scheduled_chores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scheduled Chores</h1>

<table>
  <thead>
    <tr>
      <th>Chore</th>
      <th>User</th>
      <th>Monday</th>
      <th>Tuesday</th>
      <th>Wednesday</th>
      <th>Thursday</th>
      <th>Friday</th>
      <th>Saturday</th>
      <th>Sunday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scheduled_chores.each do |scheduled_chore| %>
      <tr>
        <td><%= scheduled_chore.chore_id %></td>
        <td><%= scheduled_chore.user_id %></td>
        <td><%= scheduled_chore.monday %></td>
        <td><%= scheduled_chore.tuesday %></td>
        <td><%= scheduled_chore.wednesday %></td>
        <td><%= scheduled_chore.thursday %></td>
        <td><%= scheduled_chore.friday %></td>
        <td><%= scheduled_chore.saturday %></td>
        <td><%= scheduled_chore.sunday %></td>
        <td><%= link_to 'Show', scheduled_chore %></td>
        <td><%= link_to 'Edit', edit_scheduled_chore_path(scheduled_chore) %></td>
        <td><%= link_to 'Destroy', scheduled_chore, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scheduled Chore', new_scheduled_chore_path %>

app/views/scheduled_chores/new.html.erb
<h1>New Scheduled Chore</h1>

<%= render 'form', scheduled_chore: @scheduled_chore %>

<%= link_to 'Back', scheduled_chores_path %>

app/views/scheduled_chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Chore:</strong>
  <%= @scheduled_chore.chore_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @scheduled_chore.user_id %>
</p>

<p>
  <strong>Monday:</strong>
  <%= @scheduled_chore.monday %>
</p>

<p>
  <strong>Tuesday:</strong>
  <%= @scheduled_chore.tuesday %>
</p>

<p>
  <strong>Wednesday:</strong>
  <%= @scheduled_chore.wednesday %>
</p>

<p>
  <strong>Thursday:</strong>
  <%= @scheduled_chore.thursday %>
</p>

<p>
  <strong>Friday:</strong>
  <%= @scheduled_chore.friday %>
</p>

<p>
  <strong>Saturday:</strong>
  <%= @scheduled_chore.saturday %>
</p>

<p>
  <strong>Sunday:</strong>
  <%= @scheduled_chore.sunday %>
</p>

<%= link_to 'Edit', edit_scheduled_chore_path(@scheduled_chore) %> |
<%= link_to 'Back', scheduled_chores_path %>